---

name: Render Graphviz DOT files as PNGs

# yamllint disable-line rule:truthy
on:
  push:
  workflow_dispatch:

jobs:
  render:
    name: Render images
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v3

      - name: setup graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: render PNG images
        run: find . -iname "*.dot" -exec dot {} -O -Tpng \;

      - name: render SVG images
        run: find . -iname "*.dot" -exec dot {} -O -Tsvg \;

      - name: Create commit with changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Generate diagrams]"
          file_pattern: '*.dot.png *.dot.svg'
